import type { Metadata } from "next";

import "../styles/globals.css";
import Navbar from "@/components/navbar.";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Drukland.de",
  description: "Generated by maynuddin.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
